### ISSUE TITLE
Support for Rails 4.2

### ISSUE THREAD

**Issue by douglaslise** [rowland/activerecord-fb-adapter#47]
When using activerecord-fb-adapter with Rails 4.2 I got this error on every db operation:

    NoMethodError: undefined method `compile' for #<String:0xb382808>

The full callstack is here (called from rails console): 
https://gist.github.com/douglaslise/fbe5e82c2aad0e9d8abb

To reproduce the case, only create a new rails application from scratch using activerecord-fb-adapter and try to perform any database operation.

Thank you

**Comment by mariuz** [comment]
confirmed seems to be some changes in arel 6

**Comment by rzane** [comment]
There are definitely a lot of changes in 4.2 that need to be addressed here. 4.1 works fine, so if that's a possibility, I'd use that until this gets resolved.

**Comment by rzane** [comment]
See #56

**Comment by rzane** [comment]
I think this can be closed now, as support for 4.2 landed in 1.0.0.
