### ISSUE TITLE
Problem with column with DEFAULT ''

### ISSUE THREAD

**Issue by stenor99** [rowland/activerecord-fb-adapter#48]
Hi,

I receive "NoMethodError: undefined method `upcase' for nil:NilClass" when trying to load fixtures for a table with a column having DEFAULT '' (empty string).

Adding a nil-check in parse_default in the FbColumn class seems to have fixed the issue for me:

      def parse_default(default_source)
        default_source =~ /^\s*DEFAULT\s+(.*)\s*$/i
        return $1 unless $1.nil? || $1.upcase == "NULL"
      end

Thanks for all your work with the firebird adapter!

**Comment by rzane** [comment]
What version of ActiveRecord are you using?

**Comment by stenor99** [comment]
I am using ActiveRecord 4.1.8.
