### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by m-andreas** [rowland/activerecord-fb-adapter#58]
![console](https://cloud.githubusercontent.com/assets/2412162/7494107/11fe9bd2-f406-11e4-96fa-efcf8cb68081.jpg)

I am working on this problem now for several hours, but i cant fix it.
The default instance in the registry for firebird is set correct.
I am used the railsinstaller on win7 64 bit.
ruby 2.1.5p273
rails 4.2.1
Could you please help me with a solution, all other gems i installed so far seem to work fine.

**Comment by rowland** [comment]
We may need a Windows specialist to assist, but it looks like it's failing to find Firebird installed.

**Comment by mariuz** [comment]
maybe we need to check 64bit key in the 64 bit registry 

http://stackoverflow.com/a/13567903/66242

**Comment by mariuz** [comment]
as workaround @m-andreas try to use 32bit version for ruby/firebird until we fix it

**Comment by mariuz** [comment]
I have tested in a windows 10
 

Installed firebird 2.5.4 x64 with copy to system dir (checked)
From http://www.firebirdsql.org/en/firebird-2-5/
http://sourceforge.net/projects/firebird/files/firebird-win64/2.5.4-Release/Firebird-2.5.4.26856_0_x64.exe/download

Installed rubyinstaller x64 http://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.1.6-x64.exe
Installed Devkit 
http://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe

unzip it in C:\rubydevkit 
open cmd.exe in start->run
cd rubydevkit 
run ruby dk.rb init and ruby dk.rb install to bind it to ruby installations in your path.

then gem install fb went without issues after compilation 


I guess this can be closed

**Comment by m-andreas** [comment]
Thanks a lot!
