### ISSUE TITLE
Segfault when using spring (mac only)

### ISSUE THREAD

**Issue by rzane** [rowland/activerecord-fb-adapter#61]
This script will setup a new app using firebird:

```sh
#!/bin/bash

gem install rails -v 4.2.0 --conservative
rails _4.2.0_ new exampleapp
cd exampleapp
echo "gem 'activerecord-fb-adapter'" >> Gemfile
ruby -pi -e 'gsub(/adapter: sqlite3/, "adapter: fb\n  username: sysdba\n  password: masterkey\n  host: localhost")' config/database.yml
ruby -pi -e 'gsub(/\.sqlite3/, ".fdb")' config/database.yml
bundle install
```

Run it. Once complete, `cd exampleapp`.

Run `bin/rake db:create`. You'll get a segfaut.

Now, run it without spring `DISABLE_SPRING=1 bin/rake db:create`. It should succeed.

A similar issue exists here: https://github.com/jcupitt/ruby-vips/issues/64

~~I also suspect this issue is related: https://github.com/rowland/fb/issues/38~~

**Comment by rzane** [comment]
Removing sqlite3 from the Gemfile also seems to fix the issue.

**Comment by mariuz** [comment]
Doesn't seems to be related https://github.com/rowland/fb/issues/38

Tested Rails 4.2.3 on Win10 with both ruby/firebird 32bits or 64bits 
but again spring seems that is not supported on Windows

**Comment by rzane** [comment]
Good call @mariuz, looks like I didn't read that issue all the way.

I don't think this is an issue with the adapter or with fb, but let's keep it open for others who might come across this issue.

Strangely enough, adding `require: false` to `gem 'sqlite3'` also seems to resolve this issue.
