### ISSUE TITLE
undefined method `expr' for 30:Fixnum

### ISSUE THREAD

**Issue by Seralto** [rowland/activerecord-fb-adapter#64]
Hi,

When I add the line **gem 'activerecord-fb-adapter'** in Gemfile I got the error: **undefined method `expr' for 30:Fixnum** for pages using **will_paginate** gem.

To solve this I had to use **gem 'activerecord-fb-adapter', git: "https://github.com/rowland/activerecord-fb-adapter"**

Any clue why this happens?

Thanks.

**Comment by rowland** [comment]
Apparently that bug was fixed last September, but I had neglected to publish a new version.

Version 1.0.3 is now on rubygems.org.

**Comment by Seralto** [comment]
Thanks Rowland, using **gem 'activerecord-fb-adapter', '~> 1.0', '>= 1.0.3'** solves the problem.
