### ISSUE TITLE
Error with rake db:schema:dump

### ISSUE THREAD

**Issue by cryuff** [rowland/activerecord-fb-adapter#67]
When i execute `rake db:schema:dump` i get in schema.rb:
_Could not dump table "xxx" because of following NoMethodError
undefined method `limit' for "INTEGER":String_

and this repeat for 200 tables in my database.
I need to make app in work on exisiting database so do you know any way to fix this?
Is this problem with app or database?

This is problem with app because on new database i got this same error.
Im using flamerobin and i need to use it for creating db.

**Comment by rowland** [comment]
Can you post a table schema that causes this issue? I just tested again on a fairly large and complex database and experienced no problems.

**Comment by cryuff** [comment]
DB is uploaded here: 
http://wildcat.huzar.pl/download/do_pobrania/8647F48D4CE4409AAA5BBA7279D47410/BAZA.FDB

This is database with just one table made in flamerobin still not working this same error.

**Comment by cryuff** [comment]
Ok i just reinstall my ruby do everything from the begining (i need to move fbclient.dll from firebird install folder to Disk:ruby/bin) and now everything works great :)
