### ISSUE TITLE
Rails did not create table after ran migrations but I can retrieve and save info

### ISSUE THREAD

**Issue by LucasPiffer** [rowland/activerecord-fb-adapter#71]
activerecord-fb-adapter version: 1.0.1
Rails version: 4.2.5

What I did :
- I created a migration (with model), in Rails, and ran it.
- I started the Rails console and I was able to save records and retrieve records, like: User.all...etc;

Then I tried to look in the table (using isql-fb) to see if the database contained the tables created by migration. Surprisingly the tables were not there (even though working in rails app, what means the Rails app was being able to look inside the database).

I believe that either by rails or by isql-fb I should be able to have one committed version, right ?
What seems is that the Rails did not "commit" the change, it means: does not create the table. Since Firebird manage to deal with different changing versions provided by different users simultaneously the Rails (in this case the adapter) would not being committing the changes to the database. Does it sould reasonable? Does it sound like a bug or is it the first time that this situation is raised?

**Comment by woblavobla** [comment]
You should check - https://github.com/rowland/activerecord-fb-adapter/issues/70

**Comment by LucasPiffer** [comment]
Yes, that's true. I solved it looking at #70.

Sorry.
