### ISSUE TITLE
fb.so: undefined symbol: isc_attach_database

### ISSUE THREAD

**Issue by jan-kaczorowski** [rowland/activerecord-fb-adapter#75]
I am trying to get my Rails app working with a Firebird database as a secondary database (the default db is Postgres, where most of the data are kept, except for few models for which data should be pulled from FB database (legacy system) in read-only mode).
- The OS is Linux Mint (Ubuntu/Debian based) x64.
- Rails v. 4.2, Ruby v. 2.3.4 (MRI).
- FB Server version: `WI-V2.5.0.26074 Firebird 2.5`
- I have installed the necessary headers (`sudo apt-get install firebird-dev`)
- I do have fbclient lib: (`/usr/lib/libfbclient.so`)
- The Firebird DB server is in LAN, reachable, working, properly configured, ping'able.
```shell
$ nmap -A 192.168.10.5/32 -p 3050                                    ruby 2.3.4p301 
Starting Nmap 7.01 ( https://nmap.org ) at 2017-05-23 16:23 CEST
Nmap scan report for 192.168.10.5
Host is up (0.00055s latency).
PORT     STATE SERVICE  VERSION
3050/tcp open  firebird Firebird RDBMS Protocol version 10
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 6.74 seconds
```

**To the point:**

When I'm trying to get the data via rails console I keep getting this symbol lookup error:
**fb.so: undefined symbol: isc_attach_database**

Can it be an adapter-related issue, or would it rather be a system-related error?

![screen_issue_firebird](https://cloud.githubusercontent.com/assets/3301665/26354107/89921074-3fc3-11e7-817c-7557301af730.png)

**Comment by rowland** [comment]
The adapter makes use of the "fb" native gem, so "gem install fb" must succeed and Ruby must be of the same "bitness" (32 or 64) as the firebird package on the same machine. It appears you have fb installed, but you may wish to reinstall it and pay special attention to any messages you see.

You already said your distro is 64-bit and your firebird package appears to match, but fb.so appears not to be looking for libfbclient.so in the right place.

On my Ubuntu 16.04 staging server,

$ locate libfbclient
/usr/lib/x86_64-linux-gnu/libfbclient.so
/usr/lib/x86_64-linux-gnu/libfbclient.so.2
/usr/lib/x86_64-linux-gnu/libfbclient.so.2.5.4

which matches part of your screenshot, but I wonder if you have both 32- and 64-bit libraries installed and if fb.so is choking on the 32-bit versions.

**Comment by jan-kaczorowski** [comment]
Thank you for your tips. Solved. Turned out to be 100% system-related issue. Some of the libs were missing.

Anyone having similar problem in Ubuntu/Mint/Debian -> you may want to check if you have installed the libs listed below:


![fb-solution](https://cloud.githubusercontent.com/assets/3301665/26403737/99a98812-408f-11e7-9f2f-fc778f8c618d.png)
